const actions: Record<string, string> = {
  login: "Masuk",
  logout: "Keluar",
  token_refresh: "Pembaruan sesi",
  config_change: "Perubahan pengaturan",
  admin_accept: "Penerimaan laporan",
  admin_combine: "Penggabungan laporan",
  admin_completion_approved: "Persetujuan penyelesaian",
  admin_completion_rejected: "Permintaan perbaikan",
  admin_decide_needs_completion: "Permintaan kelengkapan",
  admin_decide_needs_survey: "Permintaan survei",
  admin_decide_rejected: "Penolakan laporan",
  admin_decide_valid: "Verifikasi laporan",
  admin_decide_duplicate: "Penetapan duplikat",
  admin_decide_out_of_scope: "Penetapan di luar cakupan",
  admin_decide_needs_clarification: "Permintaan klarifikasi",
  admin_priority_override: "Perubahan prioritas",
  ai_assessment: "Hasil AI",
  agent_approve: "Persetujuan laporan",
  agent_merge: "Penggabungan laporan",
  agent_reject: "Penolakan laporan",
  agent_request_photo: "Permintaan foto",
  location_metadata_refreshed: "Pembaruan bukti lokasi",
  anonymous_report_create: "Laporan anonim",
  report_create: "Laporan baru",
  report_update: "Perubahan laporan",
  report_assigned: "Penugasan laporan",
  report_closed: "Penutupan laporan",
  report_reopened: "Pembukaan kembali laporan",
  export_csv: "Ekspor CSV",
  export_geojson: "Ekspor GeoJSON",
  export_pdf: "Ekspor PDF",
  notification_mark_read: "Notifikasi dibaca",
  petugas_task_complete: "Penyelesaian tugas",
  petugas_task_evidence: "Penambahan bukti",
  petugas_task_progress: "Pembaruan kemajuan",
  task_started: "Pekerjaan dimulai",
  task_accepted: "Penerimaan tugas",
  task_rejected: "Penolakan tugas",
  visit_submitted: "Pengiriman survei",
  photo_uploaded: "Unggah foto",
  task_clarification: "Klarifikasi tugas",
  petugas_task_clarification: "Klarifikasi tugas",
  priority_formula_version_activate: "Aktivasi rumus prioritas",
  priority_formula_version_create: "Pembuatan rumus prioritas",
  category_create: "Penambahan fasilitas",
  category_update: "Perubahan fasilitas",
  category_delete: "Penghapusan fasilitas",
  user_create: "Penambahan pengguna",
  user_update: "Perubahan pengguna",
  user_disable: "Penonaktifan pengguna",
  unit_create: "Penambahan unit",
  unit_update: "Perubahan unit",
  unit_delete: "Penghapusan unit",
  failed_assessment_retry_success: "Pemeriksaan ulang berhasil",
  failed_assessment_retry_failed: "Pemeriksaan ulang gagal",
  failed_assessment_deleted: "Penghapusan antrean pemeriksaan",
};
const objects: Record<string, string> = {
  report: "Laporan",
  report_export: "Ekspor laporan",
  task: "Tugas",
  user: "Pengguna",
  category: "Fasilitas",
  unit: "Unit",
  notification: "Notifikasi",
  priority_formula_version: "Rumus prioritas",
  agent_tool: "Pemeriksaan AI",
};
const roles: Record<string, string> = {
  ADMIN: "Administrator",
  PETUGAS: "Petugas",
  WARGA: "Warga",
  SYSTEM: "Sistem",
};
export const auditActionLabel = (value: unknown) =>
  actions[String(value)] ?? "Kegiatan lainnya";
export const auditObjectLabel = (value: unknown) =>
  objects[String(value)] ?? "Data lainnya";
export const auditRoleLabel = (value: unknown) =>
  value == null ? "Tidak tercatat" : (roles[String(value)] ?? "Peran lainnya");
