import type { ExportJson } from "./export-data";
export const labels: Record<string, string> = {
  findings: "Temuan lapangan",
  condition: "Kondisi",
  condition_assessment: "Penilaian kondisi",
  description: "Uraian",
  notes: "Catatan",
  recommendation: "Rekomendasi",
  dimensions: "Ukuran",
  length: "Panjang",
  width: "Lebar",
  depth: "Kedalaman",
  height: "Tinggi",
  length_m: "Panjang (meter)",
  width_m: "Lebar (meter)",
  depth_m: "Kedalaman (meter)",
  height_m: "Tinggi (meter)",
  damage_type: "Jenis kerusakan",
  damage_label: "Kerusakan pada foto",
  damage_description: "Uraian kerusakan",
  severity: "Tingkat kerusakan",
  severity_label: "Tingkat kerusakan",
  safety_risk: "Risiko keselamatan",
  safety_risk_level: "Risiko keselamatan",
  population_affected: "Warga terdampak",
  impact: "Dampak",
  impact_dampak: "Dampak menurut pelapor",
  traffic_disruption: "Gangguan lalu lintas",
  accessibility: "Akses",
  item: "Pemeriksaan",
  label: "Keterangan",
  name: "Nama",
  value: "Hasil",
  checked: "Petugas memeriksa",
  required: "Pemeriksaan wajib",
  items: "Daftar pemeriksaan",
  latitude: "Lintang",
  longitude: "Bujur",
  lat: "Lintang",
  lng: "Bujur",
  accuracy: "Ketelitian lokasi (meter)",
  timestamp: "Waktu",
  status: "Status",
  reason: "Alasan",
  progress_percent: "Kemajuan pekerjaan (%)",
  progress_notes: "Catatan pekerjaan",
  completion_notes: "Catatan penyelesaian",
  title: "Judul",
  address_area: "Alamat",
  category_name: "Kategori",
  category: "Kategori",
  reported_severity: "Kerusakan menurut pelapor",
  deadline: "Batas waktu",
  duplicate_of_report_id: "Laporan tujuan penggabungan",
  merged_into: "Laporan tujuan penggabungan",
  assigned_to: "Nomor petugas",
  unit_id: "Nomor unit",
  report_id: "Nomor laporan",
  task_id: "Nomor tugas",
  photo_urls: "Foto bukti",
  summary: "Penjelasan",
  rationale: "Dasar penilaian",
  supporting_factors: "Bukti pendukung",
  risk_factors: "Hal yang perlu diperiksa",
  severity_evidence: "Kutipan tentang kerusakan",
  damage_visible: "Foto memperlihatkan kerusakan",
  quality_ok: "Foto cukup jelas",
  exposure_ok: "Pencahayaan cukup",
  resolution_ok: "Resolusi cukup",
  pii_detected: "Pemeriksaan menemukan data pribadi",
  redaction_needed: "Bukti memerlukan penyamaran",
  pii_types: "Jenis data pribadi",
  distance_meters: "Selisih lokasi (meter)",
  time_delta_hours: "Selisih waktu (jam)",
  exif_timestamp: "Waktu pengambilan foto",
  authenticity_label: "Perbandingan lokasi dan waktu",
  complete: "Laporan memuat data wajib",
  missing_fields: "Data yang perlu dilengkapi",
  duplicate_count: "Jumlah laporan serupa",
  duplication_summary: "Perbandingan laporan",
  suggested_category: "Kategori yang disarankan",
  verification_status: "Hasil pemeriksaan pekerjaan",
  safety: "Keselamatan",
  access: "Akses",
  water_depth: "Kedalaman air",
  road_width: "Lebar jalan",
  affected_area: "Luas terdampak",
  measurement: "Hasil pengukuran",
  unit: "Satuan",
  material: "Material",
  location: "Lokasi",
  evidence: "Bukti",
  additional_notes: "Catatan tambahan",
  action: "Tindakan",
  decision: "Keputusan",
  updated_at: "Waktu pembaruan",
  created_at: "Waktu pencatatan",
  id: "Nomor catatan",
  old_status: "Status sebelumnya",
  new_status: "Status sesudahnya",
  before: "Sebelum perubahan",
  after: "Sesudah perubahan",
  computed_score: "Nilai perhitungan",
  override_score: "Nilai penetapan",
  override_reason: "Alasan perubahan nilai",
  has_title: "Judul",
  has_description: "Uraian",
  has_category_id: "Kategori",
  has_location: "Lokasi",
  has_photo_urls: "Foto",
  category_id: "Kategori",
  gps_data: "Lokasi kunjungan",
  checklist: "Pemeriksaan lapangan",
  confidence: "Tingkat keyakinan",
  source: "Sumber data",
};
const words: Record<string, string> = {
  low: "ringan",
  medium: "sedang",
  high: "berat",
  critical: "kritis",
  unknown: "belum dapat ditentukan",
  good: "baik",
  poor: "buruk",
  damaged: "rusak",
  severe: "berat",
  pothole: "lubang jalan",
  crack: "retakan",
  jalan: "jalan",
  jembatan: "jembatan",
  drainase: "drainase",
  air_bersih: "air bersih",
  completed: "petugas sudah memeriksa",
  pending: "petugas belum memeriksa",
  in_progress: "petugas sedang memeriksa",
  Light: "Ringan",
  Medium: "Sedang",
  Heavy: "Berat",
};
export function value(v: ExportJson): string {
  if (v == null) return "";
  if (typeof v === "boolean") return v ? "Ya" : "Tidak";
  if (typeof v !== "object") return words[String(v)] ?? String(v);
  if (Array.isArray(v)) return v.map(value).filter(Boolean).join("; ");
  return Object.entries(v)
    .filter(([, x]) => x != null)
    .map(([k, x]) => `${labels[k] ?? k.replace(/_/g, " ")}: ${value(x)}`)
    .join("; ");
}
