/** Human-facing labels; original API values remain unchanged in technical details. */
export const valueLabels: Record<string, string> = {
  "Konsistensi EXIF berdasarkan aturan toleransi; bukan bukti keaslian":
    "Lokasi dan waktu foto sesuai dengan laporan.",
  "Skor konsistensi lokasi dan waktu belum tersedia":
    "Lokasi dan waktu foto belum dapat dicocokkan. Periksa bukti laporan atau hasil kunjungan.",
  "Perlu Verifikasi Manusia": "Perlu diperiksa",
  "Terindikasi Duplikat": "Kemungkinan laporan yang sama",
  "Kualitas Media Rendah": "Foto perlu diperbaiki",
  kritis: "Kritis",
  tinggi: "Tinggi",
  sedang: "Sedang",
  rendah: "Rendah",
  air_bersih: "Air bersih",
  clean_water: "Air bersih",
  stored_photo_exif: "Metadata foto tersimpan",
  original_photo_exif: "Metadata foto asli",
  private_original_exif: "Metadata foto asli",
  ai_assessment: "Penilaian AI",
  pending_clarification: "Menunggu penjelasan",
  clarification_requested: "Perlu penjelasan",
  risk_detected: "Risiko ditemukan",
  scanned: "Diperiksa",
  not_started: "Belum dimulai",
  submitted: "Dikirim",
  under_review: "Ditinjau",
  verified: "Terverifikasi",
  assigned: "Ditugaskan",
  accepted: "Diterima",
  in_progress: "Dikerjakan",
  completed: "Selesai",
  resolved: "Selesai",
  closed: "Ditutup",
  rejected: "Ditolak",
  approved: "Disetujui",
  needs_survey: "Perlu survei",
  needs_completion: "Perlu kelengkapan laporan",
  ADMIN: "Admin",
  PETUGAS: "Petugas",
  WARGA: "Warga",
  high: "Tinggi",
  medium: "Sedang",
  low: "Rendah",
  critical: "Kritis",
  unknown: "Belum dapat dinilai",
  mismatch: "Perlu konfirmasi",
  verifiedmatch: "Sesuai",
  none: "Tidak ada",
  jalan: "Jalan",
  jembatan: "Jembatan",
  drainase: "Drainase",
  pothole: "Lubang jalan",
  survey: "Survei",
  survei_verifikasi: "Survei verifikasi",
  perbaikan_fisik: "Perbaikan fisik",
  repair: "Perbaikan",
  initial: "Penilaian awal",
  partial: "Sebagian selesai",
  failed: "Belum berhasil",
  running: "Sedang diperiksa",
  pending: "Menunggu",
  success: "Selesai",
  uploaded_photo_exif: "Metadata foto unggahan",
  recorded_database_evidence: "Catatan lapangan tersimpan",
  no_risk: "Tidak ada risiko",
};
export const fieldLabels: Record<string, string> = {
  length: "Panjang",
  width: "Lebar",
  depth: "Kedalaman",
  height: "Tinggi",
  length_m: "Panjang (m)",
  width_m: "Lebar (m)",
  depth_m: "Kedalaman (m)",
  height_m: "Tinggi (m)",
  dimensions: "Ukuran",
  condition: "Kondisi",
  condition_assessment: "Penilaian kondisi",
  recommendation: "Rekomendasi",
  notes: "Catatan",
  item: "Pemeriksaan",
  required: "Wajib",
  checked: "Diperiksa",
  value: "Nilai",
  label: "Keterangan",
  name: "Nama",
  items: "Daftar item",
  checklist: "Daftar pemeriksaan",
  gps_data: "Lokasi kunjungan",
  accuracy: "Ketelitian lokasi",
  latitude: "Lintang",
  longitude: "Bujur",
  safety_risk_level: "Risiko keselamatan",
  impact_score: "Nilai dampak",
  safety_score: "Nilai keselamatan",
  sla_score: "Nilai waktu layanan",
  report_count: "Jumlah laporan",
  counts: "Jumlah",
  details: "Rincian",
  category_slug: "Jenis kategori",
  evidence_source: "Sumber bukti",
  gps_available: "Ketersediaan GPS",
  timestamp_available: "Ketersediaan waktu foto",
  id: "Nomor catatan",
  merged_into: "Digabung ke laporan",
  reporter_id: "Pelapor",
  rejection_reason: "Alasan penolakan",
  task_type: "Jenis tugas",
  damage_summary: "Ringkasan kerusakan",
  facility_card_id: "Nomor fasilitas",
  overall_status: "Hasil pemeriksaan",
  tool_results: "Rincian pemeriksaan",
  idempotency_key: "Kunci pengiriman",
  kecamatan: "Kecamatan",
  kelurahan: "Desa atau kelurahan",
  lat: "Lintang",
  lng: "Bujur",
  reported_severity: "Keparahan menurut pelapor",
  consent: "Persetujuan",
  supporting_case_id: "Laporan pendukung",
  priority: "Prioritas",
  address_area: "Alamat",
  created_at: "Waktu dibuat",
  device_id: "Perangkat",
  facility_card: "Data fasilitas",
  geom: "Data geografis",
  impact: "Dampak",
  impact_dampak: "Dampak terlapor",
  local_id: "Nomor lokal",
  reported_at: "Waktu dilaporkan",
  separated_into: "Dipisahkan ke laporan",
  updated_at: "Waktu diperbarui",
  verified_at: "Waktu verifikasi",
  vulnerability_index: "Indeks kerentanan",
  findings: "Temuan lapangan",
  visit_id: "Kunjungan",
  completed_at: "Waktu selesai",
  marked_read: "Sudah dibaca",
  ip: "Alamat jaringan",
  url_count: "Jumlah tautan",
  kabupaten: "Kabupaten",
  provinsi: "Provinsi",
  evidence_id: "Nomor bukti",
  photo_count: "Jumlah foto",
  estimated_completion: "Perkiraan selesai",
  activated_at: "Waktu diaktifkan",
  isActive: "Aktif",
  version: "Versi",
  weights: "Bobot penilaian",
  authenticity_label: "Kesesuaian bukti",
  consistent: "Kesesuaian lokasi dan waktu",
  authenticity_score: "Nilai kesesuaian bukti",
  exif_gps: "Koordinat foto",
  exif_timestamp: "Waktu foto",
  distance_meters: "Selisih lokasi (meter)",
  time_delta_hours: "Selisih waktu (jam)",
  complete: "Kelengkapan laporan",
  missing_fields: "Data belum tersedia",
  quality_ok: "Kelayakan foto",
  blur_score: "Ketajaman foto",
  exposure_ok: "Pencahayaan foto",
  resolution_ok: "Resolusi foto",
  damage_visible: "Kerusakan pada foto",
  damage_label: "Jenis kerusakan",
  damage_description: "Uraian kerusakan",
  severity_label: "Keparahan",
  category_name: "Kategori",
  suggested_category: "Saran kategori",
  rationale: "Pertimbangan",
  duplicates_found: "Kandidat duplikat",
  duplicate_count: "Jumlah kandidat",
  duplication_level: "Tingkat kemiripan",
  duplication_summary: "Ringkasan kemiripan",
  candidates: "Kandidat laporan",
  pii_detected: "Data pribadi",
  redaction_needed: "Perlu penyamaran",
  pii_types: "Jenis data pribadi",
  summary: "Ringkasan",
  supporting_factors: "Dasar penilaian",
  risk_factors: "Hal yang perlu diperiksa",
  correlation_ids: "Referensi catatan",
  source: "Sumber catatan",
  tasks: "Tugas",
  visits: "Kunjungan",
  checklist_template: "Daftar pemeriksaan",
  status: "Status",
  priority_score: "Prioritas",
  score: "Prioritas",
  reason: "Alasan",
  completion_notes: "Catatan selesai",
  assigned_to: "Petugas",
  unit_id: "Unit",
  task_id: "Tugas",
  report_id: "Laporan",
  verification_status: "Verifikasi",
  progress_percent: "Progres (%)",
  progress_notes: "Catatan",
  deadline: "Tenggat",
  title: "Judul",
  description: "Deskripsi",
  decision: "Keputusan",
  photo_urls: "Foto",
  completion_evidence_urls: "Foto hasil",
  instructions: "Instruksi",
  safety_risk: "Risiko keselamatan",
  safety: "Keselamatan",
  risk_level: "Tingkat risiko",
  severity: "Keparahan",
  damage_type: "Kerusakan",
  ai_assessment: "Hasil AI",
  recommended_status: "Saran status",
  ai_recommended_status: "Saran AI",
  population_affected: "Warga terdampak",
  confidence: "Keyakinan",
  category: "Kategori",
  category_id: "Kategori",
  assessments: "Hasil AI",
};
export function displayValue(value: unknown): string {
  if (value == null) return "Belum tersedia";
  if (typeof value === "boolean") return value ? "Ya" : "Tidak";
  if (Array.isArray(value)) return value.length + " item";
  if (typeof value === "object") return "Rincian tersimpan";
  return valueLabels[String(value)] ?? String(value);
}
