import { colors, surfaceColors, extendedColors, fontFamilies, fontSizes, fontWeights, lineHeights, letterSpacings, spacing, radius, shadows } from "./src/theme/tokens";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        sigap: {
          primary: colors.primary,
          primaryHover: colors.primaryDark,
          perluTindakan: colors.perluTindakan,
          diproses: colors.diproses,
          selesai: colors.selesai,
          offlineBg: surfaceColors.offlineBg,
          offlineBorder: surfaceColors.offlineBorder,
          offlineText: surfaceColors.offlineText,
          offlineDot: surfaceColors.offlineDot,
          background: colors.background,
          surface: colors.bgSurface,
          border: colors.border,
          textPrimary: colors.textPrimary,
          textSecondary: extendedColors.textSecondary,
          textTertiary: colors.textTertiary,
          textMuted: colors.textMuted,
        },
        primary: {
          50: colors.primaryLight,
          100: "#bfe0d9",
          500: colors.primary,
          600: colors.primaryDark,
          700: colors.primaryDark,
        },
        warning: {
          100: colors.warningBg,
          500: colors.warning,
          600: surfaceColors.offlineText,
        },
        danger: {
          50: colors.dangerBg,
          100: colors.dangerBg,
          500: colors.danger,
          600: extendedColors.dangerTextStrong,
          700: extendedColors.dangerTextStrong,
        },
        success: {
          50: "#f0fdf4",
          100: "#dcfce7",
          500: colors.selesai,
          600: colors.selesai,
          700: "#15803d",
        },
        info: {
          100: colors.infoBg,
          500: colors.info,
          600: "#1d4ed8",
        },
        neutral: {
          0: "#ffffff",
          50: colors.bgSurface,
          100: colors.background,
          200: colors.border,
          300: "#cfd3cc",
          400: colors.textMuted,
          500: colors.textTertiary,
          700: colors.textSecondary,
          900: colors.textPrimary,
        },
        surface: {
          sidebar: surfaceColors.sidebarBg,
          sidebarAccent: surfaceColors.sidebarAccent,
        },
      },
      spacing: spacing,
      boxShadow: {
        card: shadows.card,
        "btn-primary": shadows.buttonPrimary,
        fab: shadows.fab,
        "phone-bezel": shadows.phoneBezel,
        "map-legend": shadows.mapLegend,
        "toggle-thumb": shadows.toggleThumb,
        "browser-frame": shadows.browserFrame,
      },
      borderRadius: radius,
      fontFamily: {
        sans: fontFamilies.sans,
        mono: fontFamilies.mono,
      },
      fontSize: {
        ...fontSizes,
        "11.5": "11.5px",
        "12.5": "12.5px",
        "13.5": "13.5px",
        "17": "17px",
        "19": "19px",
      },
      fontWeight: {
        regular: fontWeights.regular,
        medium: fontWeights.medium,
        semibold: fontWeights.semibold,
        bold: fontWeights.bold,
      },
      lineHeight: lineHeights,
      letterSpacing: letterSpacings,
    },
  },
  plugins: [],
};
